# Generated by Django 3.0.3 on 2020-04-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signateur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signateur',
            old_name='image_Signateur',
            new_name='img_data',
        ),
    ]
